export const ISSUE_TYPES = {
    ERROR: "error",
    WARNING: "warning",
    INFO: "info",
};

export const ISSUE_CODES = {
    FALLBACK_MODE: 1001,
    RECOVERY_LOOP: 1002,
    SESSION_UNABLE_TO_CONNECT: 1003,
    ICE_CONNECTION_ISSUES: 1004,
    SFU_SERVER_ERROR: 1005,
    SFU_SERVER_ERROR_KNOWN: 1006,
    MEDIA_STREAM_ISSUES: 1007,
    FAILED_CONNECTION: 1008,
    NO_TURN_SERVER: 1009,
    USING_TURN_RELAY: 1010,
    MULTIPLE_ISSUES: 1012,
    SFU_LOAD_FAILED: 1013,
    SFU_CONNECT_TIMEOUT: 1014,
    SFU_CONNECT_STALLED: 1015,
    SFU_CONNECT_SLOW: 1016,
    SFU_CONNECTION_CLOSED: 1017,
    BROADCAST_CHANNEL_ISSUE: 1018,
    SELF_SESSION_REMOVED: 1019,
    ICE_CANDIDATE_MISSING_PEER: 1020,
    RECOVERY_CANDIDATE_STORM: 1021,
    AUDIO_ELEMENT_STALLED: 1022,
};

export const ANALYSIS_THRESHOLDS = {
    RECOVERY_THRESHOLD: 3,
    RECOVERY_CANDIDATE_THRESHOLD: 5,
    ICE_MISSING_PEER_THRESHOLD: 3,
    SFU_SLOW_CONNECT_MS: 5000,
    AUDIO_STALL_READY_STATE: 2,
    AUDIO_STALL_NETWORK_STATE: 3,
};
